import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePatientReport = (patient, history, riskSummary) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(40, 116, 166);
    doc.text("EpilepsyGuard Patient Report", pageWidth / 2, 20, { align: "center" });

    // Patient Info
    doc.setFontSize(12);
    doc.setTextColor(50);
    doc.text(`Patient ID: ${patient.id} `, 14, 35);
    doc.text(`Patient Name: ${patient.name} `, 14, 42);
    doc.text(`Report Date: ${new Date().toLocaleString()} `, 14, 49);

    // Risk Summary Table
    autoTable(doc, {
        startY: 60,
        head: [["Risk Level", "Reading Count", "Percentage"]],
        body: Object.entries(riskSummary).map(([level, count]) => {
            const total = Object.values(riskSummary).reduce((a, b) => a + b, 0);
            const percent = total > 0 ? ((count / total) * 100).toFixed(1) : 0;
            return [level, count, `${percent}%`];
        }),
        theme: "striped",
        headStyles: { fillColor: [40, 116, 166] },
    });

    // Vitals History Table
    doc.setFontSize(14);
    const finalY = (doc).lastAutoTable.finalY;
    doc.text("Recent Vitals History (Last 20 Readings)", 14, finalY + 15);

    autoTable(doc, {
        startY: finalY + 20,
        head: [["Time", "HR (bpm)", "SpO2 (%)", "Temp (°C)", "Risk"]],
        body: history.map(item => [
            item.time,
            item.heart_rate_bpm,
            typeof item.spo2_percent === 'number' ? item.spo2_percent.toFixed(1) : item.spo2_percent,
            typeof item.body_temperature_c === 'number' ? item.body_temperature_c.toFixed(1) : item.body_temperature_c,
            item.risk_level
        ]),
        theme: "grid",
        headStyles: { fillColor: [44, 62, 80] },
        columnStyles: {
            4: { fontStyle: "bold" }
        },
        didParseCell: (data) => {
            if (data.section === "body" && data.column.index === 4) {
                if (data.cell.raw === "High") data.cell.styles.textColor = [231, 76, 60];
                if (data.cell.raw === "Moderate") data.cell.styles.textColor = [230, 126, 34];
            }
        }
    });

    // Footer
    const footerY = doc.internal.pageSize.getHeight() - 10;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by EpilepsyGuard AI System - Provider Portal", pageWidth / 2, footerY, { align: "center" });

    // Save the PDF
    doc.save(`EpilepsyGuard_Report_${patient.id}_${Date.now()}.pdf`);
};
